### ISSUE TITLE
tex file errors

### ISSUE THREAD

**Issue by tetikshajain** [ubcgif/2021-astic-etal-gji#2]
@lheagy if you could please guide me on how to fix these errors. All the sections are commented out in the tex file and code for equations is consistent throughout the document.

1. Content in the algorithms section is not showing up.
<img width="771" alt="Screenshot 2024-07-05 at 11 37 02 AM" src="https://github.com/ubcgif/2021-astic-etal-gji/assets/126414721/a0b5fad8-b440-4fcc-a0cd-292ad792725c">

2. Some of the equations not showing up in section 13.
<img width="793" alt="Screenshot 2024-07-05 at 11 44 44 AM" src="https://github.com/ubcgif/2021-astic-etal-gji/assets/126414721/4b19a51f-e9e0-4ff2-9887-b0fdd424ad3d">

3. Text and image in section 14.
<img width="799" alt="Screenshot 2024-07-05 at 11 45 30 AM" src="https://github.com/ubcgif/2021-astic-etal-gji/assets/126414721/8a77bd08-d939-4d27-8351-1ba606c583ef">

**Comment by lheagy** [comment]
I took a pass at updating these in the pr, so we are good to go!
